//
// Created by diana on 14/8/2020.
//

#ifndef LAB03_UML_RELATIONSHIPS_PYTHON_UNIVERSITY_H
#define LAB03_UML_RELATIONSHIPS_PYTHON_UNIVERSITY_H


class University
{
    
};
#endif //LAB03_UML_RELATIONSHIPS_PYTHON_UNIVERSITY_H
